version: '3'

services:
  demo:
    image: ghcr.io/gautierbureau/demo/demo:latest
    ports:
      - 5000:80
    volumes:
      - $PWD/database.properties:/config/database.properties:Z
    restart:
      unless-stopped
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  demo-postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    command: "/init-databases.sh -c listen_addresses='*'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DEFAULT_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - $PWD/postgres/data:/var/lib/postgresql/data:Z
      - $PWD/create-postgres-databases.sh:/create-postgres-databases.sh:Z
      - $PWD/init-databases.sh:/init-databases.sh:Z
    restart:
      unless-stopped